# You should install PlaceholderAPI for placeholders.
# You have to install ProtocolLib for editing client-side max player and player count in server list.

custom-placeholders: # You can use these placeholders everywhere. You can create new ones too. (%prefix%, %warpprefix%, %spawnprefix%)
  prefix: '&8[&6SST&8]&r'
  warpprefix: '&8[&6Warps&8]&r'
  spawnprefix: '&8[&6Spawn&8]&r'
  tpaprefix: '&8[&6TPA&8]&r'
  #name: value

no-permission: '%prefix% &cI''m sorry %player% but you don''t have enough permission to do that!'
main-command-perm-required: true # if true, player must have 'sst.maincmd' permission for using '/sst' command

join-quit-messages:
  enabled: true
  first-join-message: '&9[+] &b&l%player% &7has joined to server for the first time'
  join-message: '&9[+] &b&l%player% &7has joined to server'
  quit-message: '&9[-] &b&l%player% &7has left from server'

one-more-slot:
  enabled: true # Requires ProtocolLib
  # Changes maximum player amount to player count + 1 (fake)

remove-vanished-players:
  enabled: true # Removes vanished players from client-side server list.
  # Requires ProtocolLib and won't work on BungeeCord (you won't need tho).

MOTD: # MOTD requires ProtocolLib when its enabled.
  enabled: false
  value: |
    %prefix% &aThis server is using &b&lSST&a!
    %prefix% &b&lSST&a is awesome!

auto-respawn:
  enabled: true # Removes respawn screen
  permission-required: false # sst.autorespawn

warps:
  tab-complete: true # sends warp list to client when tab button is clicked if true
  teleport-time: 5 # in second
  staff-bypass-time: true # if true, makes staff teleport immediately
  cancel-when-move:
    settings:
      block-move: true # if true, player cannot move when teleporting
      cancel-teleport: false # if true, teleport process will be cancelled when player moves
    mode: EVERYONE
    # Modes: EVERYONE, STAFF, EXCEPT_STAFF
  cancel-damage:
    settings:
      block-damage: true
      cancel-teleport: false
    mode: EVERYONE
    # Modes: EVERYONE, STAFF
    # EVERYONE: blocks damage for everyone when teleporting to warp
    # STAFF: blocks damage for staff when teleporting to warp
    # EXCEPT_STAFF: block damage for everyone except staff

tpa:
  accept-time: 10
  teleport-time: 5
  staff-bypass-time: true # if true, makes staff teleport immediately
  cancel-when-move:
    settings:
      block-move: true # if true, player cannot move when teleporting
      cancel-teleport: false # if true, teleport process will be cancelled when player moves
    mode: EVERYONE
    # Modes: EVERYONE, STAFF, EXCEPT_STAFF
  cancel-damage:
    settings:
      block-damage: true
      cancel-teleport: false
    mode: EVERYONE
    # Modes: EVERYONE, STAFF
    # EVERYONE: blocks damage for everyone when teleporting to warp
    # STAFF: blocks damage for staff when teleporting to warp
    # EXCEPT_STAFF: block damage for everyone except staff

other-messages:
  help-message:
    beginning: |
      %prefix%
      &6Arguments with [] are optional
    only-staff: |
      &9/sst reload &f- &6Reloads config.
      &9/vanish [<another player>] &f- &6Hides you (or given player) from non-staff players. Use again to disable vanish mode.
    everyone: |
      &9/warp <name> [<arguments>] &f- &6Teleports you to given warp. For help about arguments, type /sst help warpArgs.
    ending: |
      &6Arguments with [] are optional
      %prefix%
    other:
      warpArgs:
        list:
          beginning: |
            %warpprefix%
          only-staff: |
            &9/warp <name> --del &f- &6Deletes given warp.
            &9/warp <name> --force &f- &6Overwrites (if exists) given warp.
            &9/warp <name> --info &f- &6Sends information of given warp.
          everyone: |

          ending: |
            %warpprefix%
  config-reloaded: '%prefix% &eConfig has been reloaded %player%!'
  wrong-usage: '%prefix% &cWrong usage. /sst help'
  vanish:
    activated: '%prefix% &eVanish mode: &bON'
    disabled: '%prefix% &eVanish mode: &cOFF'
    toggled: '%prefix% &eVanish mode toggled for &b%other%&e.'
    player-not-found: '%prefix% &cSorry, I couldn''t find that player.'
  warps:
    created: '%warpprefix% &eYou have created a warp named &b%warp%&e!'
    deleting: '%warpprefix% &eDeleting warp &b%warp%&e...'
    deleted: '%warpprefix% &eYou have deleted the warp &b%warp%&e!'
    teleporting:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %warpprefix%
        &eTeleporting to &b%warp% &ein &b%time%...
    teleported:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %warpprefix%
        &eYou have teleported to &b%warp%
    teleport-cancelled: '%warpprefix% &cTeleport cancelled.'
    list: '%warpprefix% &eWarp list (%warpamount%): %warps%'
    no-warp: '&cThere is no warp.'
    saved: '%warpprefix% &eAll of the warps are saved into warps.yml.'
    no-permission: '%warpprefix% &cI''m sorry but you can not go to this warp.'
    info: |
      %warpprefix%
      &eInfo of warp &b%warp%
      &eLocation: &b%warpLoc%
      &ePermission: &b%warpPerm%
      %warpprefix%
  spawn:
    created: |
      %spawnprefix% &eSpawn created!
      %spawnprefix% &eLocation: &b%spawnlocation%
    changed: |
      %spawnprefix% &eSpawn location changed.
      %spawnprefix% &eNew location: &b%spawnlocation%
    teleporting:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %spawnprefix%
        &eTeleporting to &bSpawn &ein &b%time%...
    teleported:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %spawnprefix%
        &eYou have teleported to &bSpawn
    teleport-cancelled: '%spawnprefix% &cTeleport cancelled.'
    player-not-found: '%spawnprefix% &cSorry, I couldn''t find that player.'
    spawn-not-set: '%spawnprefix% &cSorry, spawn doesn''t exist.'
    not-enabled: '%spawnprefix% &cSpawn feature is not enabled.'
  gamemode:
    changed: '%prefix% &eYou have changed your gamemode to %gamemode%'
    changed-other: '%prefix% &eYou have changed %other%''s gamemode to %gamemode%'
    changed-other-2: '%prefix% &eOyun modun artık %gamemode%.'
    not-found: '%prefix% &cI couldn''t found that gamemode.'
    player-not-found: '%prefix% &cSorry, I couldn''t find that player.'
    wrong-arguments: '%prefix% &cKomutu hatalı kullandınız.'
    CREATIVE: Yaratıcı #permission: sst.gamemode.creative
    SURVIVAL: Hayatta Kalma #permission: sst.gamemode.survival
    SPECTATOR: Izleyici #permission: sst.gamemode.spectator
    ADVENTURE: Macera #permission: sst.gamemode.adventure
  fly:
    modes:
      true: aktif
      false: deaktif
    toggled: '%prefix% &6Uçuş modun artık &3%flymode%.'
    toggled-other: '%prefix% &3%other% &6adlı oyuncunun uçuş modu artık &3%flymode%.'
    type-player: '%prefix% &cBir oyuncu girmelisin.'
  god:
    modes:
      true: aktif
      false: deaktif
    toggled: '%prefix% &6Ölümsüzlük modun artık &3%godmode%.'
    toggled-other: '%prefix% &3%other% &6adlı oyuncunun ölümsüzlük modu artık &3%godmode%.'
    type-player: '%prefix% &cBir oyuncu girmelisin.'
  broadcast:
    prefix: '&7[&6Duyuru&7]&r'
    not-enough: '%prefix% &cYeterli sayıda argüman girmedin.'
  disposal:
    title: 'Çöplük'
  ping:
    message-other: '%prefix% &6%other% &eadlı oyuncunun pingi: &6%ping%'
    message: '%prefix% &3Pingin: &6%ping%'
    not-found: '%prefix% &cBir oyuncu girmelisin.'
  feed:
    message-other: '%prefix% &6%other% &eadlı oyuncunun açlığını giderdin.'
    message: '%prefix% &3Açlığını giderdin.'
    not-found: '%prefix% &cBir oyuncu girmelisin.'
  heal:
    message-other: '%prefix% &6%other% &eadlı oyuncunun canını doldurdun.'
    message: '%prefix% &3Canını doldurdun.'
    not-found: '%prefix% &cBir oyuncu girmelisin.'
  invsee:
    title: 'Zırhlar' # Sadece zırhları görüntülerken gözükür.
    not-found: '%prefix% &cGirdiğiniz oyuncu bulunamadı.'
    wrong-usage: '%prefix% &cKomutu hatalı kullandınız.'
    armor-empty: '%prefix% &cBu oyuncu hiç zırh giymiyor.'
  kick:
    broadcast:
      enabled: true
      message: '%prefix% &e%kicked% &6adlı oyuncu &e%kicker% &6tarafından sunucudan atıldı.'
    kick-message: '%prefix% &c%kicker% adlı yetkili tarafından atıldın.'
    kicked: '%prefix% &e%kicked% &3adlı oyuncuyu attın.'
    went-wrong: '%prefix% &cBir şeyler ters gitti.'
  tpa:
    request-sent: '%tpaprefix% &6You have sent a TPA request to &3%teleporting%'
    new-request: '%tpaprefix% &3%requester% &6have sent a TPA request to you'
    click-to-accept: '%tpaprefix% &6&nClick here to accept'
    click-to-deny: '%tpaprefix% &c&nClick here to deny'
    request-accepted: '%tpaprefix% &3%teleporting% &6have accepted your TPA request.'
    request-accepted-2: '%tpaprefix% &6You have accepted &3%requester%''s TPA request.'
    request-denied: '%tpaprefix% &3%teleporting% &6have denied your TPA request.'
    request-denied-2: '%tpaprefix% &6You have denied &3%requester%''s TPA request.'
    request-cancelled: '%tpaprefix% &6TPA request from &3%requester% &6cancelled by server.'
    request-cancelled-2: '%tpaprefix% &6Your TPA request that sent to &3%teleporting% &6cancelled by server.'
    no-request: '%tpaprefix% &cYou don''t have any TPA request or command was wrong.'
    went-wrong: '%tpaprefix% &cThat player didn''t send you a TPA request or something went wrong.'
    not-found: '%tpaprefix% &cYou can''t send TPA request to that user.'
    usage: '%tpaprefix% &c/tpa <player>'
    not-now: '%tpaprefix% &cYou can not send a TPA request.'
    not-now-2: '%tpaprefix% &cYou can not send a TPA request to that player for now. Try again later.'
    toggled: '%tpaprefix% &cArtık TPA isteklerini %newmode%.'
    modes:
      true: alıyorsun
      false: almıyorsun
    teleporting:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %tpaprefix%
        &eTeleporting to &b%teleporting% &ein &b%time%...
    teleported:
      mode: TITLE # Modes: ACTIONBAR, TITLE, CHAT
      message: |
        %tpaprefix%
        &eYou have teleported to &b%teleporting%
    teleport-cancelled: '%tpaprefix% &cTeleport cancelled.'